#!/bin/env bash

if [ "$#" -ne 3 ]; then
	echo "usage: $0 input output worspace"
	exit
fi

mkdir -p $3/compiler/output
cp conf/neuralart.json $3/compiler
cp conf/stm32n6.mpool $3/compiler
cp $1 $3/compiler/model.onnx
cd $3/compiler && stedgeai generate --model model.onnx --relocatable --target stm32n6 --st-neural-art default@neuralart.json --output output || exit
cp $3/compiler/output/model_OE_3_3_1.onnx $2 || exit

echo "Model ($1) compiled to $2"
